### ISSUE TITLE
Postback support

### ISSUE THREAD

**Issue by makefunstuff** [oarrabi/EXFacebook-Messenger#3]
As far as I noticed there is postback message support in TODO, is it in progress?
If it's not started can I handle this, do you accept pull requests and what is contribution guidelines?

**Comment by nsomar** [comment]
@strangeworks The contribution guidelines are pretty relaxed. And I accept any pull request :)
If you wish to handle that would be super cool!

**Comment by makefunstuff** [comment]
Okay thanks, I will submit pr asap

**Comment by nsomar** [comment]
@strangeworks Let me know if I can help you in any way :)

**Comment by makefunstuff** [comment]
I have created pull request #6, currently it requires coverage fixes.
Can you please review delete coveralls comments? 

What was changed:
* minor refactoring
* added postback support
* updated README with postback usage examples
* added postback tests but for some reasone coverage decreased, investigating currently

**Comment by nsomar** [comment]
@strangeworks fantastic!! I just merged the PR
I will update my bot with this feature...many thanks!

**Comment by makefunstuff** [comment]
I will add new facebook payload support asap(quick_reply, geocoordinate payloads etc), in order to implement fully functional facebook messenger bot.

**Comment by nsomar** [comment]
@strangeworks that would be great! 👍
